### ISSUE TITLE
Create User Controller

### ISSUE THREAD

**Issue by chibiii** [chibiii/user-management#1]
- [x] create user controller
- [x] modify default route
- [x] display temporary welcome page

**Comment by chibiii** [comment]
https://github.com/chibiii/user-management/pull/2

**Comment by chibiii** [comment]
Done with [user-management-1](https://github.com/chibiii/user-management/pull/2).
Please CR @rosoarv, thank you!

**Comment by rosoarv** [comment]
@chibiii please see my comment on the PR. thanks!
